name: yassir and younes workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome younes and yassir
              uses: actions/checkout@v4
            - name: list files
              run: ls
            - name: Read file
              run: cat README.md   
